allowBuilds:
  '@apollo/protobufjs': false
  '@nestjs/core': false
  bcrypt: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - bcrypt
onlyBuiltDependencies:
  - '@nestjs/core'
