/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
<<<<<<< Updated upstream
  NewAccount: () => import('#controllers/new_account_controller'),
=======
  Account: () => import('#controllers/account_controller'),
>>>>>>> Stashed changes
  Profile: () => import('#controllers/profile_controller'),
}
